# Define common build arguments using a YAML anchor
x-common-build-args: &common_build_args
  YT_DLP_REPO_URL: "https://github.com/Enucatl/yt-dlp.git"
  YT_DLP_COMMIT_HASH: "master"
  CARGO_PACKAGE_VERSION: "${CARGO_PACKAGE_VERSION:-unknown}"

# docker-compose.override.yml

services:
  bot:
    # Override the 'image' directive from docker-compose.yml with 'build' for local development
    build:
      context: .
      dockerfile: Dockerfile
      args:
        *common_build_args

  # This service will ONLY be activated when the 'test' profile is enabled.
  test-runner:
    profiles: ["test"] # Assign this service to the 'test' profile
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args: *common_build_args
    command: cargo test -- --nocapture

