name: Latest Dependencies

on:
  schedule:
    - cron: "22 10 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-latest-deps:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/crabberbot
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: crabberbot
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d crabberbot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Update dependencies
        run: cargo update

      - name: Run cargo test
        run: cargo test --verbose
